name: dotnet-30

on: [push]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v1

    - uses: subosito/flutter-action@v1
      with:
        flutter-version: '1.7.8+hotfix.4'

    - name: Install dependencies
      run: (cd dart-d30; flutter pub get)

    - name: Run tests
      run: (cd dart-d30; flutter pub run test)