name: Dart CI 22

on: [push]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v1

    - uses: subosito/flutter-action@v1
      with:
        flutter-version: '1.7.8+hotfix.4'

    - name: Env
      env:
        folder: dart-22

    - name: Install dependencies
      run: (cd $folder; flutter pub get)

    - name: Run tests
      run: (cd $folder; flutter pub run test)